openapi: 3.0.0
info:
  version: 1.0.0
  title: Orders
  x-ibm-name: orders
servers:
  - url: /orders
x-ibm-configuration:
  properties:
    target-url:
      value: https://sample-api.us-east-a.apiconnect.automation.ibm.com
      description: The url of the target service
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /:
    get:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
      parameters:
        - name: orderNumber
          in: path
          required: true
components:
  responses: {}
